stages:
  - build-image
  # - artifact
  - deploy
  - restart

variables:
  VUE_APP_BASE_ROUTE: "/mobile-bank-panel/"
  VUE_APP_I18N_LOCALE: "fa"
  VUE_APP_I18N_FALLBACK_LOCALE: "en"
  VUE_APP_NAME: "mobile-bank-panel"


build-image-Development:
  stage: build-image
  tags:
    - flutter-build
  script:
    - echo $VUE_APP_BASE_ROUTE
    - docker login -u $user_repository -p $pass_repository https://$repository
    - docker build 
      --build-arg VUE_APP_BASE_ROUTE=$VUE_APP_BASE_ROUTE
      --build-arg VUE_APP_I18N_LOCALE=$VUE_APP_I18N_LOCALE 
      --build-arg VUE_APP_I18N_FALLBACK_LOCALE=$VUE_APP_I18N_FALLBACK_LOCALE 
      --build-arg VUE_APP_Host=$VUE_APP_Host_Dev
      -t $CONTAINER_NAME .
    - docker tag $CONTAINER_NAME  $repository/docker/mehr/mobilebank/$CONTAINER_NAME:TestStage
    - docker push $repository/docker/mehr/mobilebank/$CONTAINER_NAME:TestStage
    - docker logout
  except:
    changes:
      - docker-compose.yml
      - PreProduct.yml
      - Product.yml 
      - .gitlab-ci.yml
  only:
    refs:
      - development

# build-image-PreProduct: 
#   stage: build-image
#   tags: 
#     - loan-build
#   script:
#     - echo $VUE_APP_Host_Pre
#     - docker login -u $user_repository -p $pass_repository https://$repository
#     - docker build 
#       --build-arg VUE_APP_BASE_ROUTE=$VUE_APP_BASE_ROUTE
#       --build-arg VUE_APP_I18N_LOCALE=$VUE_APP_I18N_LOCALE 
#       --build-arg VUE_APP_I18N_FALLBACK_LOCALE=$VUE_APP_I18N_FALLBACK_LOCALE 
#       --build-arg VUE_APP_Host=$VUE_APP_Host_Pre
#       -t $CONTAINER_NAME .
#     - docker tag $CONTAINER_NAME  $repository/docker/mehr/card-reissue/$CONTAINER_NAME:PreProduct
#     - docker push $repository/docker/mehr/card-reissue/$CONTAINER_NAME:PreProduct
#   only:
#     refs:  
#       - preproduct
#   except:
#     changes:
#       - docker-compose.yml
#       - PreProduct.yml
#       - Product.yml 
#       - .gitlab-ci.yml

# build-image-Product: 
#   stage: build-image
#   tags:
#     - loan-build
#   script:
#     - docker login -u $user_repository -p $pass_repository https://$repository
#     - docker build 
#       --build-arg VUE_APP_BASE_ROUTE=$VUE_APP_BASE_ROUTE
#       --build-arg VUE_APP_I18N_LOCALE=$VUE_APP_I18N_LOCALE 
#       --build-arg VUE_APP_I18N_FALLBACK_LOCALE=$VUE_APP_I18N_FALLBACK_LOCALE 
#       --build-arg VUE_APP_Host=$VUE_APP_Host_Pro
#       -t $CONTAINER_NAME .
#       #$VUE_APP_Host_pro should be define
#     - docker tag $CONTAINER_NAME  $repository/docker/mehr/card-reissue/$CONTAINER_NAME:Product
#     - docker push $repository/docker/mehr/card-reissue/$CONTAINER_NAME:Product
#   only:
#     refs:  
#       - master
#   except:
#     changes:
#       - docker-compose.yml
#       - PreProduct.yml
#       - Product.yml 
#       - .gitlab-ci.yml

#### Artifact section ####

# artifactory-PreProduct:
#   stage: artifact
#   tags:
#     - qmb-artifact
#   script:
#     - docker login -u $user_repository -p $pass_repository betamb.qmb.ir
#     - docker pull $repository/docker/mehr/card-reissue/$CONTAINER_NAME:PreProduct
#     - docker tag $repository/docker/mehr/card-reissue/$CONTAINER_NAME:PreProduct betamb.qmb.ir/docker/mehr/card-reissue/$CONTAINER_NAME:PreProduct
#     - docker push betamb.qmb.ir/docker/mehr/card-reissue/$CONTAINER_NAME:PreProduct
#   only: 
#     refs:
#       - preproduct
#   except:
#     changes:
#       - docker-compose.yml
#       - PreProduct.yml
#       - Product.yml 
#       - .gitlab-ci.yml

# artifactory-Product:
#   stage: artifact
#   tags:
#     - qmb-artifact
#   script:
#     - docker login -u $user_repository -p $pass_repository betamb.qmb.ir
#     - docker pull $repository/docker/mehr/card-reissue/$CONTAINER_NAME:Product
#     - docker tag $repository/docker/mehr/card-reissue/$CONTAINER_NAME:Product betamb.qmb.ir/docker/mehr/card-reissue/$CONTAINER_NAME:Product
#     - docker push betamb.qmb.ir/docker/mehr/card-reissue/$CONTAINER_NAME:Product
#   only: 
#     refs:
#       - master
#   except:
#     changes:
#       - docker-compose.yml
#       - PreProduct.yml
#       - Product.yml 
#       - .gitlab-ci.yml

#### Deploy section ####

Development:
  stage: deploy
  tags:
    - prep
  script:
      - docker pull $repository/docker/mehr/mobilebank/$CONTAINER_NAME:TestStage
      - docker-compose --compatibility  up -d
  when : manual
  only:
    - development
   
# PreProduct:
#   stage: deploy
#   tags: 
#     - bank-preproduct
#   script:
#     - ls -la
#     - docker stack deploy -c PreProduct.yml $PRE_STACK_NAME
#   when : manual
#   only:
#     - preproduct

# Product:
#   stage: deploy
#   tags: 
#     - bank-preproduct
#   script:
#     - ls
#     - docker stack deploy -c Product.yml $STACK_NAME
#   when : manual
#   only:
#     - master

#### Restart section ####

Development-restart:
  stage: restart
  tags: 
    - prep
  script:
    - docker-compose down
    - docker-compose --compatibility up -d
  only:
    - development
  when: manual

# PreProduct-restart:
#   stage: restart
#   tags:
#     -  bank-preproduct
#   script:
#     - docker stack rm $PRE_STACK_NAME
#     - docker stack deploy -c PreProduct.yml $PRE_STACK_NAME 
#   only:  
#     - preproduct
#   when: manual

# Product-restart:
#   stage: restart
#   tags:
#     -  bank-preproduct
#   script:
#     - docker stack rm $STACK_NAME
#     - docker stack deploy -c Product.yml $STACK_NAME
#   only:
#     - master
#   when: manual



