stages:
  - build-image
  - artifact
  - deploy
  - restart

variables:
  VUE_APP_BASE_ROUTE: "/online-deposit-panel/"
  VUE_APP_I18N_LOCALE: "fa"
  VUE_APP_I18N_FALLBACK_LOCALE: "en"
  VUE_APP_NAME: "online deposit panel"
#  VUE_APP_Host: "https://mehrmb.asr24.com/deposit-panel-backend/"

#### Build Image section ####
build-image-Development:
  stage: build-image
  tags:
    - loan-build
  script:
    - docker login -u $user_repository -p $pass_repository https://$repository
    - docker build
      --build-arg VUE_APP_BASE_ROUTE=$VUE_APP_BASE_ROUTE
      --build-arg VUE_APP_I18N_LOCALE=$VUE_APP_I18N_LOCALE
      --build-arg VUE_APP_I18N_FALLBACK_LOCALE=$VUE_APP_I18N_FALLBACK_LOCALE
      -t $CONTAINER_NAME .
    - docker tag $CONTAINER_NAME  $repository/docker/ada/$CONTAINER_NAME:TestStage
    - docker push $repository/docker/ada/$CONTAINER_NAME:TestStage
  only:
    - development

build-image-PreProduct:
  stage: build-image
  tags:
    - loan-build
  script:
    - docker login -u $user_repository -p $pass_repository https://$repository
    - docker build
      --build-arg VUE_APP_BASE_ROUTE=$VUE_APP_BASE_ROUTE
      --build-arg VUE_APP_I18N_LOCALE=$VUE_APP_I18N_LOCALE
      --build-arg VUE_APP_I18N_FALLBACK_LOCALE=$VUE_APP_I18N_FALLBACK_LOCALE
      -t $CONTAINER_NAME .
    - docker tag $CONTAINER_NAME  $repository/docker/ada/$CONTAINER_NAME:PreProduct
    - docker push $repository/docker/ada/$CONTAINER_NAME:PreProduct
  only:
    - preproduct

#### Artifact section ####

artifactory-PreProduct:
  stage: artifact
  tags:
    - qmb-artifact
  script:
    - docker login -u $user_repository -p $pass_repository betamb.qmb.ir
    - docker pull $repository/docker/ada/$CONTAINER_NAME:PreProduct
    - docker tag $repository/docker/ada/$CONTAINER_NAME:PreProduct betamb.qmb.ir/docker/ada/$CONTAINER_NAME:PreProduct
    - docker push betamb.qmb.ir/docker/ada/$CONTAINER_NAME:PreProduct
  only:
    refs:
      - preproduct

artifactory-Product:
  stage: artifact
  tags:
    - qmb-artifact
  script:
    - docker login -u $user_repository -p $pass_repository betamb.qmb.ir
    - docker pull $repository/docker/ada/$CONTAINER_NAME:Product
    - docker tag $repository/docker/ada/$CONTAINER_NAME:Product betamb.qmb.ir/docker/ada/$CONTAINER_NAME:Product
    - docker push betamb.qmb.ir/docker/ada/$CONTAINER_NAME:Product
  only:
    refs:
      - master

#### Deploy section ####

Development:
  stage: deploy
  tags:
    - prep
  script:
    - docker pull $repository/docker/ada/$CONTAINER_NAME:TestStage
    - docker-compose --compatibility  up -d
  when : manual
  only :
    - development
PreProduct:
  stage: deploy
  tags:
    -  bank-preproduct
  script:
    - docker stack deploy -c PreProduct.yml $PRE_STACK_NAME
  when : manual
  only :
    - preproduct

#### Restart section ####

Development-restart:
  stage: restart
  tags:
    - prep
  script:
    - docker-compose down
    - docker-compose --compatibility up -d
  only:
    - development
  when: manual

PreProduct-restart:
  stage: restart
  tags:
    -  bank-preproduct
  script:
    - docker stack rm $PRE_STACK_NAME
    - docker stack deploy -c PreProduct.yml $PRE_STACK_NAME
  only:
    - preproduct
  when: manual

Product-restart:
  stage: restart
  tags:
    -  bank-preproduct
  script:
    - docker stack rm $STACK_NAME
    - docker stack deploy -c Product.yml $STACK_NAME
  only:
    - master
  when: manual

