version: "3.8"
services:
  mobilebank-panel-client:
    image: $repository/docker/mehr/mobilebank/$CONTAINER_NAME:TestStage
    container_name: $CONTAINER_NAME
    hostname: $CONTAINER_NAME
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    labels:
      - "collect_logs_with_filebeat=true"
      - "decode_log_event_to_json_object=true"
    networks:
      - loan-net
    ports:
      - 8006:8003
    environment:
      - EUREKA_SERVER=http://discovery:8761/myeureka/eureka
      - TZ=UTC-3:30
    env_file:
      - .env_development

networks:
  loan-net:
    name: loan-net
    external: true
