version: "3.8"
services:
  mobile-bank-panel-client:
    image: betamb.qmb.ir/docker/mehr/mobilebank/$CONTAINER_NAME:PreProduct
    container_name: $PRE_STACK_NAME
    hostname: $PRE_STACK_NAME
    labels:
      - "collect_logs_with_filebeat=true"
      - "decode_log_event_to_json_object=true"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 6
      placement:
        constraints:
          - node.labels.stage == preproduct
          - node.labels.name == manager3
    networks:
      - preproduct
      - proxy
    env_file:
      - .env
    environment:
      - EUREKA_SERVER=http://pre-discovery:8761/myeureka/eureka
      - TZ=Asia/Tehran
    extra_hosts:
      - "hamrahbank.qmb.ir:10.82.3.22"


networks:
  preproduct:
    name: preproduct
    external: true
  proxy:
    name: proxy
    external: true
