version: "3.8"
services:
  mobile-bank-panel-client:
    image: betamb.qmb.ir/docker/mehr/mobilebank/$CONTAINER_NAME:Product
    container_name: $STACK_NAME
    hostname: $STACK_NAME
    labels:
      - "collect_logs_with_filebeat=true"
      - "decode_log_event_to_json_object=true"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 6
      placement:
        constraints:
          - node.labels.stage == product
          - node.labels.zone == dmz
    env_file:
      - .env
    ports:
      - 8084:8003
    environment:
      - TZ=Asia/Tehran
    networks:
      - product
      - proxy

networks:
  product:
    name: product
    external: true
  proxy:
    name: proxy
    external: true
