version: "3.8"
services:
  online-deposit-panel:
    image: betamb.qmb.ir/docker/$CONTAINER_NAME:Product
    hostname: online-deposit-panel
    labels:
      - "collect_logs_with_filebeat=true"
      - "decode_log_event_to_json_object=true"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 6
      placement:
        constraints:
          - node.labels.stage == product
          - node.labels.zone == dmz
    env_file:
      - .env
    environment:
      - TZ=Asia/Tehran
    networks:
      - product
      - proxy

networks:
  product:
    name: product
    external: true
  proxy:
    name: proxy
    external: true
